### ISSUE TITLE
32 bit out of memory | Folders with many files crash

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/prefetch#56]
Yes, the program crashed, and my guess is that it's because of the large number of files (although I could be wrong since when I prefetch rimworld there were 48306 lines in the prefetch.cache.ini file) because prefetch crashes when I scan the folder with the stable diffusion neural network and the folder with my anaconda virtual environments (I have 26 virtual environments).

I am using Windows 11 22H2, Ryzen 5 5600X, GTX 1660 6GB GDDR5 10Ghz, 32 GB DDR4 Ram CL16.

**Comment by mhtvsSFrpHdE** [comment]
To debug, I have few ideas:

    Look at these file, if one of them >= 3.5 GB, use a x64 build, this is 32 bit out of memory
    You've mentioned when path contains "-", it will crash
    Too many files beyond limitations of QT ini file
    Too many files beyond limitations of C++ int (2147483647)

You may also 7-zip your problem folder and prefetch config,
send them to me via BitTorrent, Mega online storage, OneDrive share, Syncthing, or anything you familiar with.

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW I attached a debugger, and if I load "Stable-diffusion\NovelAI\model.ckpt",  
Qt return nothing instead of 32 bit out of memory crash.

Besides, the file read is run threaded, so I may think it will crash that thread by first, instead of the entire program.

Name contains "-" will not cause crash #57 
Please continue to upload all your files for debug purpose.

**Comment by AndreyRGW** [comment]
> @AndreyRGW I attached a debugger, and if I load "Stable-diffusion\NovelAI\model.ckpt", Qt return nothing instead of 32 bit out of memory crash.
> 
> Besides, the file read is run threaded, so I may think it will crash that thread by first, instead of the entire program.
> 
> Name contains "-" will not cause crash #57 Please continue to upload all your files for debug purpose.

@mhtvsSFrpHdE I tried adding a folder to the prefetch that contains exclusively models for stable diffusion (they all have about the same size - 4,265,377,440 bytes) and surprisingly prefetch did not crash. Then, I added the virtual environment folder for stable diffusion and prefetch didn't crash either. The models folder and the virtual environment folder weigh the most in the stable diffusion folder. The other folders weigh 2363 MB. Now it seems to me that the problem is not the weight.

**Comment by AndreyRGW** [comment]
My experiment continues: I moved these two folders - with virtual environment and models to a separate folder and tried to add them to prefetch, prefetch crashed out.

**Comment by AndreyRGW** [comment]
I deleted one more model and the total weight was 15gb and prefetch didn't crash.

**Comment by AndreyRGW** [comment]
I put that model back and prefetch crashed when standbylist was at 5gb.

**Comment by AndreyRGW** [comment]
So, prefetch does not crash when two folders weigh 15gb in total, but it crashes when they weigh 17gb. In both cases I had 22gb of free RAM. I wonder what the problem is.

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW

No need to do too much inefficient test, once I have all the files, debugger will tell me crash point and reason.  
Of course, having a folder as small as possible but can crash the program is nice.  
You can use exist Syncthing folder or submit a new share.

I'm currently doing the code to read file 50 MB a time, so prefetch file larger than 3.5 GB with 32 bit is possible.

**Comment by AndreyRGW** [comment]
> @AndreyRGW
> 
> No need to do too much inefficient test, once I have all the files, debugger will tell me crash point and reason. Of course, having a folder as small as possible but can crash the program is nice. You can use exist Syncthing folder or submit a new share.
> 
> I'm currently doing the code to read file 50 MB a time, so prefetch file larger than 3.5 GB with 32 bit is possible.

 I guess I'll cancel the sync with stable diffusion and anaconda folders and add a folder with those two folders ( virtual environment for stable diffusion and models ) that together causes the crash.

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW Then I'll delete `Conda` and `StableDiffusion`.

Expect this config will cause crash:
```
[PrefetchFolder]
cf=C:\\CrashFolders

[ExcludeFolder]

[PriorityIncludePattern]
```

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW The reason does is 32 bit out of memory.  
Sometimes Qt return empty array, so the file is skipped and no crash.  
But sometimes Qt throw `std::bad_alloc`: I don't write any catch in my code, unhandled throw, crash happen.  
QTimer warning is just normal behavior during unclean shutdown.

If I use a buffer to read file and use maximum 64 MB, there is no `std::bad_alloc`.

Once the test is done, I'll upload a new version.

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW https://github.com/mhtvsSFrpHdE/prefetch/releases/tag/4.0.2  
See [ReadBufferSize](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#readbuffersize---int) for more details
